### ISSUE TITLE
Option to add aria-label

### ISSUE THREAD

**Issue by thdoan** [rehypejs/rehype-external-links#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

For external links I'd like to add `aria-label="(opens in a new window)"` to the `<a>` tag. It would be great if there was an option to do this, e.g.:

```
  markdown: {
    rehypePlugins: [
      [
        rehypeExternalLinks, {
          ariaLabel: '(opens in new window)',
          protocols: ['http', 'https', 'mailto'],
          rel: [],
          target: '_blank',
        }
      ],
    ],
  },
```

### Solution

Add `ariaLabel` option as seen above.

### Alternatives

For more flexibility, maybe offer a way to add any custom attribute, similar to `options.contentProperties` but which applies to `<a>`.

**Comment by wooorm** [comment]
Hi!

I like the alternative you propose better than adding more and more properties on the options object itself.

It’s slightly weird that `target` and `rel` are on the root options object, if there’s also a `linkProperties` or so. And which should get precedence if `linkProperties.rel` is set?

And what name to use? Maybe `properties` is fine?

One thing to think about: those properties need to be deep cloned, because `rel` or `className` could be arrays. And there are other values allowed.

Would you be interested in working on a PR?
Would be something like https://github.com/rehypejs/rehype-autolink-headings/blob/a37d231c4c0c29c6880d8e1b6842dfbd771027dc/lib/index.js#L21-L24, https://github.com/rehypejs/rehype-autolink-headings/blob/a37d231c4c0c29c6880d8e1b6842dfbd771027dc/lib/index.js#L108. With a default of `{}` I think. And then `rel` and `target` are preferred over `properties.rel`/`properties.target`?

**Comment by wooorm** [comment]
I don‘t think this is a good use of ARIA btw. Not only screen readers need to know where your link goes. Everyone does.

**Comment by thdoan** [comment]
There's still no consensus on this, but I think I got the idea from these two sources:

https://it.wisc.edu/learn/make-it-accessible/develop-accessible-websites/when-to-open-links-in-a-new-tab/
https://www.digitala11y.com/external-links-in-or-out/

My bad for using a bad example -- it should really include the destination as recommended in the articles.
